# Archivo base para la creaci칩n de un servidor Docker-DinD que usa autenticaci칩n basada 
# en TLS. Puedes utilizar los valores por defecto simplemente ejecutando en esta carpeta 
# el siguiente comando:

  #> docker compose up

# Tambien puedes cambiar el nombre del servidor usando el archivo 
# "docker-compose-cambio-nombre-servidor.yml", y puedes cambiar las claves y certificados 
# con el archivo "docker-compose-cambio-pki.yml".

services:
  docker-dind:
    image: tfg2asircanaveral2024/docker-dind:seguro
    # exponer los puertos al exterior es opcional, si los contenedores que vayan a 
    # interactuar con este contenedor est치n en su misma red, se podr치n comunicar sin 
    # publicar los puertos
    ports:
      - 2376:2376
      - 4243:4243
    privileged: true
    user: "0"

    volumes:
      # el archivo de configuracion del daemon de docker, daemon.json, se encuentra en 
      # la carpeta ./configuracion-docker. El fichero ya existe en el contenedor, pero 
      # con este punto de montaje, es sustituido por el archivo de este directorio 
      # llamado daemon.json, que puede ser editado por los usuarios antes de lanzar el 
      # contenedor
      - ./configuracion-docker:/etc/docker/:ro

    networks:
      - red-1

networks:
  red-1:
    driver: bridge